---
title: "Exploring BikeTown Data"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
if (!require(tmap)) {
  install.packages("tmap")
  library(tmap)
}

```

## Mapping the "hubs"
A trip can start or end at one of the designated hubs, or it can start or end at an arbitrary point. In our dataset, the hubs are designated by name, usually a street intersection, and the arbitrary endpoints are designated by their GPS coordinates.

So let's map the hubs and other endpoints.
```{r}
tmap_mode("view")
hub_map <- qtm(biketown_hubs_sp)
save_tmap(hub_map, filename = "biketown_hubs.html")
print(hub_map)
```

```{r}
trip_summary <- biketown_cleaned %>% group_by(StartHub, EndHub) %>% 
  summarize(
    trips = n(),
    median_miles = median(Distance_Miles),
    IQR_miles = IQR(Distance_Miles),
    median_hours = median(duration_hours),
    IQR_hours = IQR(duration_hours),
    median_mph = median(mph),
    IQR_mph = IQR(mph)) %>% 
  mutate(start_equals_end = (StartHub == EndHub)) %>% 
  arrange(desc(trips))

```

